// ============================================================
// data.js — Datos iniciales migrados del Excel del grupo
// ============================================================

const INITIAL_DATA = {
  boteInicial: 270,
  participantes: [
    { id: 1, nombre: "Jandro", aportacion: 30 },
    { id: 2, nombre: "Finchi", aportacion: 30 },
    { id: 3, nombre: "Tiki", aportacion: 30 },
    { id: 4, nombre: "Willy", aportacion: 30 },
    { id: 5, nombre: "Mive", aportacion: 30 },
    { id: 6, nombre: "Fori", aportacion: 30 },
    { id: 7, nombre: "Rado", aportacion: 30 },
    { id: 8, nombre: "Grillo", aportacion: 30 },
    { id: 9, nombre: "Roi", aportacion: 30 },
  ],
  apuestas: [
    {
      id: 1,
      partido: "México - Sudáfrica",
      apuesta: "Ganador México + No goles en los 10 primeros mins",
      cuota: 1.86,
      importe: 20,
      posibleGanancia: 37.2,
      estado: "perdida",
    },
    {
      id: 2,
      partido: "México - Sudáfrica",
      apuesta: "México -1,5",
      cuota: 2.3,
      importe: 10,
      posibleGanancia: 23.0,
      estado: "ganada",
    },
    {
      id: 3,
      partido: "Corea del Sur - Chequia",
      apuesta: "X2 Chequia",
      cuota: 1.44,
      importe: 20,
      posibleGanancia: 28.8,
      estado: "perdida",
    },
    {
      id: 4,
      partido: "Corea del Sur - Chequia",
      apuesta: "Ambos marcan",
      cuota: 1.95,
      importe: 15,
      posibleGanancia: 29.25,
      estado: "ganada",
    },
    {
      id: 5,
      partido: "Canadá - Bosnia",
      apuesta: "Ganador Canadá",
      cuota: 1.8,
      importe: 15,
      posibleGanancia: 27.0,
      estado: "perdida",
    },
    {
      id: 6,
      partido: "Canadá - Bosnia",
      apuesta: "Ambos marcan",
      cuota: 2.05,
      importe: 10,
      posibleGanancia: 20.5,
      estado: "ganada",
    },
    {
      id: 7,
      partido: "EEUU - Paraguay",
      apuesta: "Ganador EEUU",
      cuota: 2.05,
      importe: 10,
      posibleGanancia: 20.5,
      estado: "ganada",
    },
    {
      id: 8,
      partido: "Catar - Suiza",
      apuesta: "Primero en anotar Suiza",
      cuota: 2.0,
      importe: 10,
      posibleGanancia: 20.0,
      estado: "ganada",
    },
    {
      id: 9,
      partido: "Catar - Suiza",
      apuesta: "Suiza -2,5",
      cuota: 2.6,
      importe: 10,
      posibleGanancia: 26.0,
      estado: "perdida",
    },
    {
      id: 10,
      partido: "Brasil - Marruecos",
      apuesta: "Ambos marcan",
      cuota: 2.1,
      importe: 15,
      posibleGanancia: 31.5,
      estado: "ganada",
    },
    {
      id: 11,
      partido: "Brasil - Marruecos",
      apuesta: "Gol del muerto de Igor Thiago",
      cuota: 2.75,
      importe: 5,
      posibleGanancia: 13.75,
      estado: "perdida",
    },
    {
      id: 12,
      partido: "Alemania - Curazao",
      apuesta: "Ambos marcan NO y +2,5 goles",
      cuota: 1.72,
      importe: 20,
      posibleGanancia: 34.4,
      estado: "perdida",
    },
    {
      id: 13,
      partido: "Holanda - Japón",
      apuesta: "Ganador Holanda",
      cuota: 2.05,
      importe: 10,
      posibleGanancia: 20.5,
      estado: "perdida",
    },
    {
      id: 14,
      partido: "Suecia - Túnez",
      apuesta: "Ganador Suecia",
      cuota: 1.85,
      importe: 15,
      posibleGanancia: 27.75,
      estado: "ganada",
    },
    {
      id: 15,
      partido: "Costa de Marfil - Ecuador",
      apuesta: "Ganador Ecuador",
      cuota: 2.55,
      importe: 15,
      posibleGanancia: 38.25,
      estado: "perdida",
    },
    {
      id: 16,
      partido: "España - Cabo Verde",
      apuesta: "España -2,5",
      cuota: 1.65,
      importe: 15,
      posibleGanancia: 24.75,
      estado: "perdida",
    },
    {
      id: 17,
      partido: "Bélgica - Egipto",
      apuesta: "Bélgica y +1,5 goles",
      cuota: 1.83,
      importe: 10,
      posibleGanancia: 18.3,
      estado: "perdida",
    },
    {
      id: 18,
      partido: "Bélgica - Egipto",
      apuesta: "Salah y De Bruyne tiran a puerta",
      cuota: 4.5,
      importe: 5,
      posibleGanancia: 22.5,
      estado: "ganada",
    },
    {
      id: 19,
      partido: "Uruguay - Arabia Saudí",
      apuesta: "Gana Uruguay y portería a cero",
      cuota: 2.1,
      importe: 15,
      posibleGanancia: 31.5,
      estado: "perdida",
    },
    {
      id: 20,
      partido: "Irán - Nueva Zelanda",
      apuesta: "Gana Irán y -3,5 goles",
      cuota: 2.15,
      importe: 20,
      posibleGanancia: 43.0,
      estado: "perdida",
    },
  ],
};
